### ISSUE TITLE
Regarding the license

### ISSUE THREAD

**Issue by ghost** [accodeing/dimage#1]
The repo has no LICENSE (or COPYING or similar) file so it's proprietary, I assume you just forgot to add it?

Also I've noticed that there's a binary artifact (dimage) in the repo root.

**Comment by d-Pixie** [comment]
@Yardanico sorry for late reply. You are correct that I forgot about the license, it is ofc open source - MIT. I'll fix that and remove the binary as soon as I have some time 🙂 Thanks for the ticket.
